
# This file is automatically generated, you probably don't want to edit this

aiExplainOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiExplainOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            input_text = "",
            ollama_url = "http://localhost:11434/v1/chat/completions",
            model_name = "deepseek-r1:14b",
            system_prompt = "B\u1EA1n l\u00E0 m\u1ED9t chuy\u00EAn gia ph\u00E2n t\u00EDch s\u1ED1 li\u1EC7u. H\u00E3y \u0111\u1ECDc n\u1ED9i dung b\u1EA3ng d\u1EEF li\u1EC7u sau v\u00E0 vi\u1EBFt m\u1ED9t \u0111o\u1EA1n gi\u1EA3i th\u00EDch ng\u1EAFn g\u1ECDn, chu\u1EA9n h\u1ECDc thu\u1EADt b\u1EB1ng ti\u1EBFng Vi\u1EC7t.", ...) {

            super$initialize(
                package="jamoviAI",
                name="aiExplain",
                requiresData=FALSE,
                ...)

            private$..input_text <- jmvcore::OptionString$new(
                "input_text",
                input_text,
                default="")
            private$..ollama_url <- jmvcore::OptionString$new(
                "ollama_url",
                ollama_url,
                default="http://localhost:11434/v1/chat/completions")
            private$..model_name <- jmvcore::OptionString$new(
                "model_name",
                model_name,
                default="deepseek-r1:14b")
            private$..system_prompt <- jmvcore::OptionString$new(
                "system_prompt",
                system_prompt,
                default="B\u1EA1n l\u00E0 m\u1ED9t chuy\u00EAn gia ph\u00E2n t\u00EDch s\u1ED1 li\u1EC7u. H\u00E3y \u0111\u1ECDc n\u1ED9i dung b\u1EA3ng d\u1EEF li\u1EC7u sau v\u00E0 vi\u1EBFt m\u1ED9t \u0111o\u1EA1n gi\u1EA3i th\u00EDch ng\u1EAFn g\u1ECDn, chu\u1EA9n h\u1ECDc thu\u1EADt b\u1EB1ng ti\u1EBFng Vi\u1EC7t.")

            self$.addOption(private$..input_text)
            self$.addOption(private$..ollama_url)
            self$.addOption(private$..model_name)
            self$.addOption(private$..system_prompt)
        }),
    active = list(
        input_text = function() private$..input_text$value,
        ollama_url = function() private$..ollama_url$value,
        model_name = function() private$..model_name$value,
        system_prompt = function() private$..system_prompt$value),
    private = list(
        ..input_text = NA,
        ..ollama_url = NA,
        ..model_name = NA,
        ..system_prompt = NA)
)

aiExplainResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiExplainResults",
    inherit = jmvcore::Group,
    active = list(
        text_output = function() private$.items[["text_output"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Kết quả xử lý từ Local AI")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text_output",
                title="\u0110o\u1EA1n v\u0103n b\u1EA3n t\u1EF1 \u0111\u1ED9ng gi\u1EA3i th\u00EDch"))}))

aiExplainBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiExplainBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviAI",
                name = "aiExplain",
                version = c(1,0,0),
                options = options,
                results = aiExplainResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Local AI
#'
#' 
#' @param input_text .
#' @param ollama_url .
#' @param model_name .
#' @param system_prompt .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text_output} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
aiExplain <- function(
    input_text = "",
    ollama_url = "http://localhost:11434/v1/chat/completions",
    model_name = "deepseek-r1:14b",
    system_prompt = "B\u1EA1n l\u00E0 m\u1ED9t chuy\u00EAn gia ph\u00E2n t\u00EDch s\u1ED1 li\u1EC7u. H\u00E3y \u0111\u1ECDc n\u1ED9i dung b\u1EA3ng d\u1EEF li\u1EC7u sau v\u00E0 vi\u1EBFt m\u1ED9t \u0111o\u1EA1n gi\u1EA3i th\u00EDch ng\u1EAFn g\u1ECDn, chu\u1EA9n h\u1ECDc thu\u1EADt b\u1EB1ng ti\u1EBFng Vi\u1EC7t.") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("aiExplain requires jmvcore to be installed (restart may be required)")


    options <- aiExplainOptions$new(
        input_text = input_text,
        ollama_url = ollama_url,
        model_name = model_name,
        system_prompt = system_prompt)

    analysis <- aiExplainClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

