
# This file is automatically generated, you probably don't want to edit this

apiAIOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "apiAIOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            input_text = "",
            api_url = "https://api.openai.com/v1/chat/completions",
            api_key = "",
            model_name = "gpt-4o-mini",
            system_prompt = "B\u1EA1n l\u00E0 m\u1ED9t chuy\u00EAn gia ph\u00E2n t\u00EDch s\u1ED1 li\u1EC7u. H\u00E3y \u0111\u1ECDc n\u1ED9i dung b\u1EA3ng d\u1EEF li\u1EC7u sau v\u00E0 vi\u1EBFt m\u1ED9t \u0111o\u1EA1n gi\u1EA3i th\u00EDch ng\u1EAFn g\u1ECDn, chu\u1EA9n h\u1ECDc thu\u1EADt b\u1EB1ng ti\u1EBFng Vi\u1EC7t.", ...) {

            super$initialize(
                package="jamoviAI",
                name="apiAI",
                requiresData=FALSE,
                ...)

            private$..input_text <- jmvcore::OptionString$new(
                "input_text",
                input_text,
                default="")
            private$..api_url <- jmvcore::OptionString$new(
                "api_url",
                api_url,
                default="https://api.openai.com/v1/chat/completions")
            private$..api_key <- jmvcore::OptionString$new(
                "api_key",
                api_key,
                default="")
            private$..model_name <- jmvcore::OptionString$new(
                "model_name",
                model_name,
                default="gpt-4o-mini")
            private$..system_prompt <- jmvcore::OptionString$new(
                "system_prompt",
                system_prompt,
                default="B\u1EA1n l\u00E0 m\u1ED9t chuy\u00EAn gia ph\u00E2n t\u00EDch s\u1ED1 li\u1EC7u. H\u00E3y \u0111\u1ECDc n\u1ED9i dung b\u1EA3ng d\u1EEF li\u1EC7u sau v\u00E0 vi\u1EBFt m\u1ED9t \u0111o\u1EA1n gi\u1EA3i th\u00EDch ng\u1EAFn g\u1ECDn, chu\u1EA9n h\u1ECDc thu\u1EADt b\u1EB1ng ti\u1EBFng Vi\u1EC7t.")

            self$.addOption(private$..input_text)
            self$.addOption(private$..api_url)
            self$.addOption(private$..api_key)
            self$.addOption(private$..model_name)
            self$.addOption(private$..system_prompt)
        }),
    active = list(
        input_text = function() private$..input_text$value,
        api_url = function() private$..api_url$value,
        api_key = function() private$..api_key$value,
        model_name = function() private$..model_name$value,
        system_prompt = function() private$..system_prompt$value),
    private = list(
        ..input_text = NA,
        ..api_url = NA,
        ..api_key = NA,
        ..model_name = NA,
        ..system_prompt = NA)
)

apiAIResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "apiAIResults",
    inherit = jmvcore::Group,
    active = list(
        text_output = function() private$.items[["text_output"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Kết quả xử lý từ API AI")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text_output",
                title="\u0110o\u1EA1n v\u0103n b\u1EA3n t\u1EF1 \u0111\u1ED9ng gi\u1EA3i th\u00EDch"))}))

apiAIBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "apiAIBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviAI",
                name = "apiAI",
                version = c(1,0,0),
                options = options,
                results = apiAIResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' API AI
#'
#' 
#' @param input_text .
#' @param api_url .
#' @param api_key .
#' @param model_name .
#' @param system_prompt .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text_output} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
apiAI <- function(
    input_text = "",
    api_url = "https://api.openai.com/v1/chat/completions",
    api_key = "",
    model_name = "gpt-4o-mini",
    system_prompt = "B\u1EA1n l\u00E0 m\u1ED9t chuy\u00EAn gia ph\u00E2n t\u00EDch s\u1ED1 li\u1EC7u. H\u00E3y \u0111\u1ECDc n\u1ED9i dung b\u1EA3ng d\u1EEF li\u1EC7u sau v\u00E0 vi\u1EBFt m\u1ED9t \u0111o\u1EA1n gi\u1EA3i th\u00EDch ng\u1EAFn g\u1ECDn, chu\u1EA9n h\u1ECDc thu\u1EADt b\u1EB1ng ti\u1EBFng Vi\u1EC7t.") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("apiAI requires jmvcore to be installed (restart may be required)")


    options <- apiAIOptions$new(
        input_text = input_text,
        api_url = api_url,
        api_key = api_key,
        model_name = model_name,
        system_prompt = system_prompt)

    analysis <- apiAIClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

